### ISSUE TITLE
Add user agent for azure so the azure cli can pick it up

### ISSUE THREAD

**Issue by VinozzZ** [getporter/terraform-mixin#103]
TODO: Determine if it's possible to set the user agent of the azure resource provider

**Comment by carolynvs** [comment]
Here's a search of user agent in the azure rm provider. AWS implements a customizable user agent so I have hope we can too! https://github.com/search?q=repo%3Ahashicorp%2Fterraform-provider-azurerm%20user%20agent&type=code

**Comment by carolynvs** [comment]
Sounds like we just need to set the standard azure user agent env var and the azure resource will pick it up, same for aws as well. 

https://github.com/hashicorp/terraform-provider-azurerm/issues/2393

We can have the terraform mixin inject these env vars (like the az and aws mixins do today, but with opt-out) when their respective cloud resource providers are used.
