### ISSUE TITLE
Bump dependency versions

### ISSUE THREAD

**Issue by jonnyry** [getporter/terraform-mixin#119]
Hello

Could I request a version bump in dependencies -

Docker Scout is reporting a number of CVEs:

![image](https://github.com/user-attachments/assets/1c2984b8-587a-4677-89b0-28b272002584)

...

![image](https://github.com/user-attachments/assets/2bdea474-83d8-4624-8472-2892ee42dfc7)

![image](https://github.com/user-attachments/assets/f2106683-a77d-4525-9dde-2f9f2117ac92)

![image](https://github.com/user-attachments/assets/e8d52db8-6327-4727-b46d-13854645e7d9)

etc

Many thanks.

**Comment by marrobi** [comment]
@schristoff are you able to merge these PRs from dependabot:

https://github.com/getporter/terraform-mixin/pull/112
https://github.com/getporter/terraform-mixin/pull/110

Then create a new release which I believe should update the Go stdlib version as the runner will have a more recent version of Go installed.

Many thanks for the support.

**Comment by schristoff** [comment]
Fixed in v1.0.4, thank you! :)

**Comment by jonnyry** [comment]
Hi @schristoff many thanks for rebuilding, the number of CVEs has dropped dramatically:

![image](https://github.com/user-attachments/assets/d0b90e54-2e06-4d40-8d26-cc5a56f04aaf)

One thing I had to do was specify the `canary` release:

```
porter mixin install terraform --version canary
```

Is it possible to add the new version into your atom release feed so I can specify by version number?  Or if you can tell me the URL to pass as a `--url` param - I did try various permutations but couldn't discover the right one?

Many thanks
