### ISSUE TITLE
Remove temporary zip file in docker build to trim the porter invocation image

### ISSUE THREAD

**Issue by jasmdk** [getporter/terraform-mixin#60]
When installing the terraform binary (https://github.com/getporter/terraform-mixin/blob/174d233556c4fe36df78abd2f238b2550662d346/pkg/terraform/build.go) a zip file is downloaded and unzipped, but the zip file remains and adds an unnecessary 33 MB from an image which already is quite large

**Comment by ThorstenHans** [comment]
I'll take this one 🎉
