### ISSUE TITLE
Unable to pass objects into terraform plan

### ISSUE THREAD

**Issue by crosbygw** [getporter/terraform-mixin#89]
Hi!
I receive the following error when passing an object into terraform plan configured with object variable:

err: could unmarshal input:
 upgrade:
  - terraform:
      vars:
        client_settings:
          create_instance: "true"
        prefix: deployment
: yaml: unmarshal errors:
  line 5: cannot unmarshal !!map into string
Error: could unmarshal input:
 upgrade:
  - terraform:
      description: Create BIG-IP Next on VIO
      vars:
        client_settings:
          create_instance: "true"
        prefix: deployment
: yaml: unmarshal errors:
  line 5: cannot unmarshal !!map into string
1 error occurred:
        * mixin execution failed: exit status 1

1 error occurred:
        * container exit code: 1, message: <nil>

Here is example porter config:

upgrade:
  - terraform:
      vars:
        prefix: "{{bundle.parameters.prefix}}"
        client_settings: {"client_settings":"true"}

Would be great if terraform mixin supported passing objects into plan.

**Comment by carolynvs** [comment]
When you find out what the proper way to call the terraform cli and pass in an object variable at the command line, if you could drop that here, it will help with getting a fix out sooner.

**Comment by sgettys** [comment]
> When you find out what the proper way to call the terraform cli and pass in an object variable at the command line, if you could drop that here, it will help with getting a fix out sooner.

I'll take a look at this and work with Greg on getting a fix in!

**Comment by sgettys** [comment]
Terraform cli to run this:
terraform plan --var file_contents="foo!" --var map_var='{"foo": "bar"}'
