### ISSUE TITLE
Use terraform provider mirror at buildtime?

### ISSUE THREAD

**Issue by carolynvs** [getporter/terraform-mixin#90]
See this discussion for context: https://github.com/getporter/porter/discussions/2279#discussioncomment-3324975

In some cases, just calling terraform init isn't sufficient to avoid calls back to download providers at runtime, particularly when a remote backend is being used (since we call init again in that case). Looks like we should also call mirror so that the second call to init at runtime grabs the files from the bundle and not by redownloading the provider files.

**Comment by tamirkamara** [comment]
@carolynvs is this something we can do? I can take it...

**Comment by carolynvs** [comment]
@tamirkamara absolutely, I would really appreciate help getting this resolved sooner.

Here is the code that I think needs to be changed:

https://github.com/getporter/terraform-mixin/blob/465b0462ce5d1d9f0abd7a5137084e1f87e959ac/pkg/terraform/build.go#L11-L18

If you have any questions, just let me know. 👍

**Comment by tamirkamara** [comment]
When running the mirror it duplicated the data that was fetched by the init command. In my custom docker file I delete the data downloaded by the init command and everything works fine. I have bundles with 5 terraform plugins and that accounts for ~300MB that are saved.

How do I know in the build time if an init will be run during runtime? `init.go` includes some logic around it but I wasn't sure if an init would always run or not...
