### ISSUE TITLE
compile failure tf version  v0.10.0 with porter v1.0 on beta3

### ISSUE THREAD

**Issue by squillace** [getporter/terraform-mixin#92]
repro:

1. install porter v1.0-beta3
2. porter create foo
3. porter mixin install terraform (receive  v0.10.0)
4. modify the porter.yaml file to merely reference the `- terraform` mixin
5. porter build

expected: I am a good person on this horrible planet

received:

    squillace@dellsquill:~/work/squillace/pwc$ porter mixins list
    ---------------------------------------------
      Name       Version        Author
    ---------------------------------------------
      atlas      v0.0.0         ralph squillace
      az         v0.7.3         Porter Authors
      exec       v1.0.0-beta.3  Porter Authors
      terraform  v0.10.0        Porter Authors
    squillace@dellsquill:~/work/squillace/pwc$ porter build
    exit status 1
    exit status 1
    exit status 1
    Copying porter runtime ===>
    Copying mixins ===>
    Copying mixin exec ===>
    Copying mixin az ===>
    Copying mixin atlas ===>
    Copying mixin terraform ===>
    Building invocation image
    [+] Building 2.5s (19/26)
     => [internal] load build definition from Dockerfile                                                                                                                                             0.0s
     => => transferring dockerfile: 1.90kB                                                                                                                                                           0.0s
     => [internal] load .dockerignore                                                                                                                                                                0.0s
     => => transferring context: 35B                                                                                                                                                                 0.0s
     => resolve image config for docker.io/docker/dockerfile-upstream:1.4.0                                                                                                                          0.1s
     => CACHED docker-image://docker.io/docker/dockerfile-upstream:1.4.0@sha256:178c4e4a93795b9365dbf6cf10da8fcf517fcb4a17f1943a775c0f548e9fc2ff                                                     0.0s
     => [internal] load .dockerignore                                                                                                                                                                0.0s
     => [internal] load build definition from Dockerfile                                                                                                                                             0.0s
     => [internal] load metadata for docker.io/library/debian:stretch-slim                                                                                                                           0.1s
     => [internal] load build context                                                                                                                                                                1.4s
     => => transferring context: 187.14MB                                                                                                                                                            1.4s
     => [stage-0  1/18] FROM docker.io/library/debian:stretch-slim@sha256:abaa313c7e1dfe16069a1a42fa254014780f165d4fd084844602edbe29915e70                                                           0.0s
     => CACHED [stage-0  2/18] RUN useradd nonroot -m -u 65532 -g 0 -o                                                                                                                               0.0s
     => CACHED [stage-0  3/18] RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache                                0.0s
     => CACHED [stage-0  4/18] RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt     apt-get update && apt-get install -y ca-certificates                          0.0s
     => CANCELED [stage-0  5/18] RUN apt-get update && apt-get -y install gnupg wget && wget -qO - https://pgp.mongodb.com/server-5.0.asc | apt-key add - && echo "deb [ arch=amd64,arm64 ] https:/  1.7s
     => CACHED [stage-0  6/18] RUN apt-get update && apt-get install -y apt-transport-https lsb-release gnupg curl                                                                                   0.0s
     => CACHED [stage-0  7/18] RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.asc.gpg                                             0.0s
     => CACHED [stage-0  8/18] RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list                          0.0s
     => CACHED [stage-0  9/18] RUN apt-get update && apt-get install -y azure-cli                                                                                                                    0.0s
     => CACHED [stage-0 10/18] RUN apt-get update && apt-get install -y wget unzip &&  wget https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip &&  unzip terraform_1.0.  0.0s
     => ERROR [stage-0 11/18] COPY terraform/ /cnab/app/terraform/                                                                                                                                   0.0s
    ------
     > [stage-0 11/18] COPY terraform/ /cnab/app/terraform/:
    ------
    error building docker image: failed to solve: failed to compute cache key: "/terraform" not found: not found
    unable to build CNAB invocation image: error building docker image: failed to solve: failed to compute cache key: "/terraform" not found: not found
    unable to build CNAB invocation image: error building docker image: failed to solve: failed to compute cache key: "/terraform" not found: not found

**Comment by squillace** [comment]
a touch more clarity on the failing line:

 => [stage-0  1/18] FROM docker.io/library/debian:stretch-slim@sha256:abaa313c7e1dfe16069a1a42fa254014780f165d4fd084844602edbe29915e70                                                                                                                                                                                                            0.0s
 => CACHED [stage-0  2/18] RUN useradd nonroot -m -u 65532 -g 0 -o                                                                                                                                                                                                                                                                                0.0s
 => CACHED [stage-0  3/18] RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache                                                                                                                                                                                 0.0s
 => CACHED [stage-0  4/18] RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt     apt-get update && apt-get install -y ca-certificates                                                                                                                                                                           0.0s
 => CANCELED [stage-0  5/18] RUN apt-get update && apt-get install -y wget unzip &&  wget https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip &&  unzip terraform_1.0.4_linux_amd64.zip -d /usr/bin &&  rm terraform_1.0.4_linux_amd64.zip                                                                             2.6s
 => ERROR [stage-0  6/18] COPY terraform/ /cnab/app/terraform/                                                                                                                                                                                                                                                                                    0.0s
------
 > [stage-0  6/18] COPY terraform/ /cnab/app/terraform/:
------
error building docker image: failed to solve: failed to compute cache key: "/terraform" not found: not found
unable to build CNAB invocation image: error building docker image: failed to solve: failed to compute cache key: "/terraform" not found: not found
unable to build CNAB invocation image: error building docker image: failed to solve: failed to compute cache key: "/terraform" not found: not found

**Comment by squillace** [comment]
well this was a nice work out: https://github.com/getporter/terraform-mixin#workingdir describes that it presumes the working directory for tf files is /terraform but I didn't realize it defaulted in a directory (which doesn't exist) and the result is that the mixin build complains that there's no directory. :-) Imagine! 

I'll close this in the morning....

**Comment by carolynvs** [comment]
Sounds like we should keep this open and either add a better error for when the terraform working directory doesn't exist.

**Comment by squillace** [comment]
or if we HAVE a default directory and it doesn't exist, just create it. I mean, we can fail, or we can have an empty directory that affects nothing until it begins to be used. ????

**Comment by squillace** [comment]
closing as dupe of https://github.com/getporter/terraform-mixin/issues/62 :-)
